### ISSUE TITLE
Investigate automatically setting up env vars on review apps

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-visitor#631] opened 2019-01-15 15:32 UTC
At the moment we have to manually enter them. There's only one, but still...

**Comment by astroash** [comment] 2019-01-15 15:52
This issue is partially caused by us needing different env vars for `production` and `staging || PR-review-apps`. 
Things I have tried:

![whatsapp image 2018-12-06 at 14 25 23](https://user-images.githubusercontent.com/14337958/51191696-db24bb00-18dc-11e9-985d-136d95b0a379.jpeg)
- selecting inherit config vars from staging. Sounds like it should work (and has previously), but is not working. I think it is  because `app.json` does not specify these env vars as required, however I cannot find documentation to confirm this.

- looking into adding env specific config to `app.json`. You can specify what env vars are needed in different environments, however by default heroku spins all node apps up in `production` env.

**Comment by astroash** [comment] 2019-02-13 10:17
I think env vars arent being pulled from staging to review app as they are not set as required in the app.json. One work around would be to set all env vars as required (`PROXY_API_URL` & `OTHER_CONFIG_OPTION`), but explicitly setting the ones that we dont want to use to something obviously wrong eg `NOT_SET`. Then we can filter out the option set as `NOT_SET`

**Comment by astroash** [comment] 2019-03-22 07:26
Closing due to decision to move away from `staging` branches & creating a monorepo

https://github.com/TwinePlatform/hq/issues/63
https://github.com/TwinePlatform/hq/issues/62

**Closed by astroash** 2019-03-22 07:26 UTC
Labels: 4️⃣ priority-4
